import { useState } from 'react'
import { X } from 'lucide-react'
import { Field } from './AuthForm.jsx'
import { prettyLabel } from '../utils/finance.js'

export default function RecordModal({ type, record, onClose, onSubmit, loading, error }) {
  const isExpense = type === 'expense'
  const choices = isExpense ? ['HOUSING', 'TRANSPORTATION', 'FOOD', 'UTILITIES', 'HEALTHCARE', 'ENTERTAINMENT', 'SHOPPING', 'EDUCATION', 'TRAVEL', 'PERSONAL', 'DEBT', 'OTHER'] : ['SALARY', 'FREELANCE', 'BUSINESS', 'INVESTMENTS', 'GIFT', 'OTHER']
  const methods = ['CASH', 'DEBIT_CARD', 'CREDIT_CARD', 'BANK_TRANSFER', 'DIGITAL_WALLET', 'DIRECT_DEBIT', 'OTHER']
  const [form, setForm] = useState(record || { amount: '', date: new Date().toISOString().slice(0, 10), description: '', [isExpense ? 'category' : 'source']: '', ...(isExpense ? { paymentMethod: '' } : {}) })
  const [validationError, setValidationError] = useState('')
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = (event) => { event.preventDefault(); if (!form.amount || Number(form.amount) <= 0) return setValidationError('Amount must be greater than zero.'); if (!form[isExpense ? 'category' : 'source']) return setValidationError(`Choose a valid ${isExpense ? 'category' : 'source'}.`); if (!form.date) return setValidationError('Choose a valid date.'); if (isExpense && !form.paymentMethod) return setValidationError('Choose a payment method.'); setValidationError(''); onSubmit({ ...form, amount: Number(form.amount) }) }
  return <div className="modal-backdrop"><section className="record-modal"><div className="modal-heading"><div><p className="eyebrow">{record ? 'Update record' : 'New record'}</p><h2>{record ? `Edit ${isExpense ? 'expense' : 'income'}` : `Add ${isExpense ? 'expense' : 'income'}`}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20} /></button></div><form className="record-form" onSubmit={submit}>{(error || validationError) && <div className="form-alert">{error || validationError}</div>}<Field label="Amount" type="number" min="0.01" step="0.01" value={form.amount} onChange={update('amount')} placeholder="0.00" required /><label className="field"><span>{isExpense ? 'Category' : 'Source'}</span><select value={form[isExpense ? 'category' : 'source']} onChange={update(isExpense ? 'category' : 'source')} required><option value="">Select {isExpense ? 'category' : 'source'}</option>{choices.map((choice) => <option key={choice} value={choice}>{prettyLabel(choice)}</option>)}</select></label><Field label="Date" type="date" value={form.date} onChange={update('date')} required /><Field label="Description" type="text" maxLength="500" value={form.description || ''} onChange={update('description')} placeholder="Add a note" />{isExpense && <label className="field"><span>Payment method</span><select value={form.paymentMethod} onChange={update('paymentMethod')} required><option value="">Select payment method</option>{methods.map((method) => <option key={method} value={method}>{prettyLabel(method)}</option>)}</select></label>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={loading}>{loading ? 'Saving...' : record ? 'Save changes' : 'Add record'}</button></div></form></section></div>
}