apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-expense-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-expense-backend
  template:
    metadata:
      labels:
        app: smart-expense-backend
    spec:
      containers:
        - name: backend
          image: 182312754343.dkr.ecr.ap-south-1.amazonaws.com/smart-expense-budget-manager-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres:5432/smart_expense_db
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smart-expense-secret
                  key: database-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-expense-secret
                  key: jwt-secret
            - name: JWT_EXPIRATION
              value: "86400000"
            - name: SERVER_PORT
              value: "8080"
            - name: FRONTEND_URL
              value: http://smart-expense-frontend
