apiVersion: v1
kind: Service
metadata:
  name: smart-expense-frontend
spec:
  selector:
    app: smart-expense-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
