apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-expense-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-expense-frontend
  template:
    metadata:
      labels:
        app: smart-expense-frontend
    spec:
      containers:
        - name: frontend
          image: smart-expense-budget-manager-frontend:latest
          ports:
            - containerPort: 80
