apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-expense-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-expense-frontend
  template:
    metadata:
      labels:
        app: smart-expense-frontend
    spec:
      containers:
        - name: frontend
          image: 182312754343.dkr.ecr.ap-south-1.amazonaws.com/smart-expense-budget-manager-frontend:latest
          ports:
            - containerPort: 80
