import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, CheckCircle2, LoaderCircle } from 'lucide-react'
import { AuthShell, Field, FormAlert } from '../components/AuthForm.jsx'
import { useAuth } from '../context/AuthContext.jsx'

export default function Register() {
  const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ fullName: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false); const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.fullName.trim()) return setError('Enter your full name.'); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return setError('Enter a valid email address.'); if (form.password.length < 8) return setError('Password must be at least 8 characters.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setLoading(true); try { await register({ fullName: form.fullName.trim(), email: form.email, password: form.password }); setSuccess(true); setTimeout(() => navigate('/login'), 1200) } catch (registrationError) { setError(registrationError.message || 'We could not create your account.') } finally { setLoading(false) } }
  return <AuthShell eyebrow="Get started" title="Create your account" footer={<>Already have an account? <Link to="/login">Sign in <ArrowRight size={14} /></Link></>}><form onSubmit={submit} className="auth-form"><FormAlert>{error}</FormAlert>{success && <div className="success-alert"><CheckCircle2 size={18} /> Account created. Redirecting to sign in...</div>}<Field label="Full name" type="text" autoComplete="name" value={form.fullName} onChange={update('fullName')} placeholder="Jordan Lee" /><Field label="Email address" type="email" autoComplete="email" value={form.email} onChange={update('email')} placeholder="you@example.com" /><div className="field-row"><Field label="Password" type="password" autoComplete="new-password" value={form.password} onChange={update('password')} placeholder="8+ characters" /><Field label="Confirm password" type="password" autoComplete="new-password" value={form.confirmPassword} onChange={update('confirmPassword')} placeholder="Repeat password" /></div><button className="primary-button" disabled={loading || success}>{loading ? <LoaderCircle className="spin" size={18} /> : 'Create account'}{!loading && !success && <ArrowRight size={18} />}</button></form></AuthShell>
}